# Generated by Django 3.2.8 on 2021-10-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_tags_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
